import { BriefcaseBusiness, Building2, CalendarDays, CarFront, CircleHelp, FileText, Gift, Info, MapPinned, Plane, ShieldCheck, Sparkles, Users, type LucideIcon } from 'lucide-react'

export type PublicPageData = { eyebrow:string; title:string; intro:string; icon:LucideIcon; cards:{title:string;text:string}[] }
const standard = (title:string,text:string) => ({title,text})
export const publicPages: Record<string,PublicPageData> = {
  services:{eyebrow:'Managed mobility services',title:'The right service for the way you need to move.',intro:'Immediate, scheduled, airport, executive, corporate, event and interstate transportation — coordinated as one professional operation.',icon:CarFront,cards:[standard('On-demand rides','Request an immediate ride and a managed vehicle is assigned from available FASTRIDES capacity.'),standard('Scheduled transport','Reserve important journeys and recurring movement ahead of time.'),standard('Managed requirements','Coordinate chauffeurs, events, executives and multi-vehicle assignments.')]},
  membership:{eyebrow:'FASTRIDES membership',title:'Priority, predictability and more personal mobility.',intro:'Membership is built around convenience and access, with four plans shaped around how often — and how importantly — you travel.',icon:Sparkles,cards:[standard('FASTRIDES Access','Everyday convenience, member support and eligible shared mobility.'),standard('Executive & Signature','Stronger allocation, credits, airport value and concierge-style support.'),standard('FASTRIDES Royale','Personalised executive mobility and relationship-led service where available.')]},
  safety:{eyebrow:'Safety and accountability',title:'A clear chain of responsibility for every journey.',intro:'FASTRIDES combines verified records, controlled permissions, trip status, SOS workflows and incident review — so every journey stays accountable.',icon:ShieldCheck,cards:[standard('Know the trip','Driver, vehicle, passenger and timestamps are linked to the authorised journey.'),standard('Location with purpose','Location is collected only with your permission during operationally necessary states.'),standard('Escalation workflows','SOS and incidents capture context for authorised support and review teams.')]},
  about:{eyebrow:'About FASTRIDES',title:'A Nigerian mobility brand built to manage more than rides.',intro:'FASTRIDES, operated by Dreamz Transportz Servicez (DTS), bridges everyday ride access, professional chauffeur service and serious managed fleet operations.',icon:Info,cards:[standard('Premium but practical','Professional service designed for everyday users and high-value clients.'),standard('Managed operations','Drivers, vehicles, availability and service quality are professionally controlled.'),standard('Built to expand','New cities, vehicle classes and services are added as operations confirm them.')]},
  chauffeur:{eyebrow:'Professional chauffeur service',title:'A chauffeur experience shaped around your schedule.',intro:'Reserve an eligible vehicle and trained FASTRIDES chauffeur for hourly, executive, airport or event requirements.',icon:BriefcaseBusiness,cards:[standard('Hourly service','Book defined chauffeur time with clear service rules.'),standard('Executive movement','Coordinate important meetings, guests and leadership travel.'),standard('Preferred chauffeurs','Eligible members can express a preference, subject to availability.')]},
  'airport-transfers':{eyebrow:'Airport transfers',title:'Arrivals and departures, properly planned.',intro:'Dedicated airport booking captures flight reference, luggage, meet-and-greet preference, waiting rules and vehicle requirements.',icon:Plane,cards:[standard('Abuja airport','Nnamdi Azikiwe International Airport is supported as our first configured airport.'),standard('Clear waiting rules','Applicable complimentary time and charges appear before confirmation.'),standard('Flight-aware planning','Flight details are captured with your booking; live flight status arrives with our aviation partner.')]},
  events:{eyebrow:'Event transportation',title:'One movement plan for every vehicle, chauffeur and guest.',intro:'Coordinate weddings, conferences, delegations, group airport transfers and private events with multi-vehicle dispatch.',icon:CalendarDays,cards:[standard('Multi-vehicle planning','Assign vehicles, chauffeurs, manifests and pickup schedules.'),standard('Operations view','Monitor statuses and coordinate changes during the event.'),standard('Client reporting','Keep bookings, service notes and billing linked to the event.')]},
  interstate:{eyebrow:'Pre-booked interstate',title:'Intercity journeys with controlled routes and rules.',intro:'Abuja ↔ Kaduna is our first configured route. New routes open as operations confirm them.',icon:MapPinned,cards:[standard('Route-based service','Distance, estimated time, days, pricing and classes are planned per route.'),standard('Pre-booked by default','Same-day service appears only when explicitly enabled for a route.'),standard('Operational care','Availability can respond to service windows and route conditions.')]},
  contact:{eyebrow:'Contact & support',title:'Talk to the right FASTRIDES team.',intro:'Customer, chauffeur, corporate and safety support are organised through categorised tickets and accountable resolution.',icon:CircleHelp,cards:[standard('Customer support','Booking, payment, membership, rewards and lost-item help.'),standard('Corporate support','Billing, policy and managed account assistance.'),standard('Safety escalation','Structured incident context for authorised operations teams.')]},
  faq:{eyebrow:'Frequently asked questions',title:'Clear answers before your journey.',intro:'Find practical information about booking, estimates, waiting time, membership, shared rides, payments and cancellations.',icon:CircleHelp,cards:[standard('Are estimates guaranteed?','Only when the pricing engine marks a fare as fixed.'),standard('Is FASTRIDES Share public pooling?','No. It is controlled, eligibility-based member mobility with a maximum of four passengers.'),standard('Where does FASTRIDES operate?','Abuja and Lagos are active today; new cities open as operations confirm them.')]},
  privacy:{eyebrow:'Privacy',title:'Personal information deserves careful handling.',intro:'FASTRIDES minimises location collection, restricts sensitive access and supports retention, account and audit controls.',icon:FileText,cards:[standard('Location privacy','No permanent customer tracking simply because the PWA is installed.'),standard('Access controls','Sensitive records are limited by role and operational purpose.'),standard('User requests','Account deletion and privacy request workflows are supported.')]},
  terms:{eyebrow:'Terms of service',title:'Clear responsibilities for a managed mobility service.',intro:'These terms describe how the FASTRIDES service is delivered, what you can expect from us, and what we ask of you.',icon:FileText,cards:[standard('Service eligibility','Availability depends on city, time, class and operational rules.'),standard('Customer conduct','Passengers and bookers must provide accurate journey information.'),standard('Platform use','Access remains subject to account security and acceptable-use controls.')]},
  'cancellation-policy':{eyebrow:'Cancellation policy',title:'Know the applicable rule before confirming.',intro:'Cancellation windows, charges, no-show treatment and membership or corporate exceptions are shown clearly before you confirm.',icon:FileText,cards:[standard('Free window','Each service has a clearly stated free cancellation window.'),standard('Visible before payment','Applicable rules are presented in the confirmation flow.'),standard('Auditable changes','Policy changes are recorded for accountability.')]},
  rewards:{eyebrow:'FASTREWARDS',title:'Recognition for meaningful loyalty.',intro:'Points recognise eligible rides, referrals, reviews and milestones. Points are not cash — they are loyalty recognition with configured value.',icon:Gift,cards:[standard('Earn transparently','Every points entry records its rule and source.'),standard('Redeem configured value','Rewards may include credits, upgrades and waiting-time benefits.'),standard('Expiry and history','Members can see earning, redemption and expiry activity.')]},
  referrals:{eyebrow:'FASTRIDES referrals',title:'Invite people you trust. Track every outcome.',intro:'Eligible members receive a code, referral link and reward history, with qualification rules and fraud controls built in.',icon:Users,cards:[standard('Rewarded when qualified','Rewards are issued once the configured qualifying action completes.'),standard('Fraud controls','Self-referral and duplicate-account checks support review.'),standard('Clear value','Rewards, limits and expiry are defined by the programme.')]},
  fleet:{eyebrow:'Managed fleet operations',title:'Every vehicle treated as an operating asset.',intro:'Vehicle records connect assignment, compliance, service, cost, revenue and contribution.',icon:Building2,cards:[standard('Complete vehicle file','Class, fuel type, documents, mileage and service history.'),standard('Driver assignment','Current and historical chauffeur assignments remain auditable.'),standard('Contribution context','Operational estimates are clearly separated from accounting statements.')]},
}