import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'

export const roleEnum = pgEnum('user_role', ['customer','driver','fleet_manager','admin','corporate_admin','corporate_rider','super_admin'])
export const bookingStatusEnum = pgEnum('booking_status', ['DRAFT','PENDING_PAYMENT','CONFIRMED','SEARCHING_DRIVER','DRIVER_ASSIGNED','DRIVER_EN_ROUTE','DRIVER_ARRIVED','PASSENGER_ONBOARD','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW','INCIDENT','REFUNDED'])
export const sharedStatusEnum = pgEnum('shared_ride_status', ['AVAILABLE','MATCHING','MATCHED','PICKUP_PENDING','PICKING_UP','IN_TRANSIT','DROPPING_OFF','COMPLETED','CANCELLED'])
export const fuelTypeEnum = pgEnum('fuel_type', ['PETROL','DIESEL','HYBRID','ELECTRIC'])
export const paymentStatusEnum = pgEnum('payment_status', ['PENDING','PROCESSING','SUCCEEDED','FAILED','REFUNDED','CANCELLED'])

const timestamps = { createdAt: timestamp('created_at',{withTimezone:true}).defaultNow().notNull(), updatedAt: timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(), deletedAt: timestamp('deleted_at',{withTimezone:true}) }

export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(), identityId: text('identity_id').notNull(), email: text('email').notNull(), phone: text('phone'), fullName: text('full_name').notNull(), role: roleEnum('role').default('customer').notNull(), status: text('status').default('ACTIVE').notNull(), marketingConsent: boolean('marketing_consent').default(false).notNull(), termsAcceptedAt: timestamp('terms_accepted_at',{withTimezone:true}), privacyAcceptedAt: timestamp('privacy_accepted_at',{withTimezone:true}), lastLoginAt: timestamp('last_login_at',{withTimezone:true}), ...timestamps,
}, (table) => [uniqueIndex('users_identity_id_idx').on(table.identityId), uniqueIndex('users_email_idx').on(table.email), index('users_role_idx').on(table.role)])

export const customerProfiles = pgTable('customer_profiles', {
  id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id,{onDelete:'cascade'}), dateOfBirth: date('date_of_birth'), profilePhotoUrl: text('profile_photo_url'), businessName: text('business_name'), preferredVehicleClassId: uuid('preferred_vehicle_class_id'), preferredPickup: jsonb('preferred_pickup'), emergencyContactName: text('emergency_contact_name'), emergencyContactPhone: text('emergency_contact_phone'), corporateAccountId: uuid('corporate_account_id').references(() => corporateAccounts.id), verificationStatus: text('verification_status').default('UNVERIFIED').notNull(), status: text('status').default('ACTIVE').notNull(), acquisitionSource: text('acquisition_source'), preferences: jsonb('preferences').default({}).notNull(), ...timestamps,
}, (table) => [uniqueIndex('customer_profiles_user_idx').on(table.userId)])

export const cities = pgTable('cities', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), state: text('state').notNull(), country: text('country').default('Nigeria').notNull(), active: boolean('active').default(false).notNull(), operatingHours: jsonb('operating_hours').default({}).notNull(), settings: jsonb('settings').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('cities_name_state_idx').on(table.name,table.state)])
export const operatingZones = pgTable('operating_zones', { id: uuid('id').defaultRandom().primaryKey(), cityId: uuid('city_id').notNull().references(() => cities.id), name: text('name').notNull(), zoneType: text('zone_type').notNull(), geometry: jsonb('geometry').notNull(), active: boolean('active').default(true).notNull(), sharedRideEnabled: boolean('shared_ride_enabled').default(false).notNull(), ...timestamps }, (table) => [index('zones_city_idx').on(table.cityId)])

export const vehicleClasses = pgTable('vehicle_classes', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), description: text('description').default('').notNull(), passengerCapacity: integer('passenger_capacity').notNull(), luggageCapacity: integer('luggage_capacity').default(0).notNull(), sharedRideEligible: boolean('shared_ride_eligible').default(false).notNull(), active: boolean('active').default(true).notNull(), attributes: jsonb('attributes').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('vehicle_classes_code_idx').on(table.code)])
export const vehicles = pgTable('vehicles', { id: uuid('id').defaultRandom().primaryKey(), vehicleCode: text('vehicle_code').notNull(), vehicleClassId: uuid('vehicle_class_id').notNull().references(() => vehicleClasses.id), cityId: uuid('city_id').references(() => cities.id), make: text('make').notNull(), model: text('model').notNull(), year: integer('year').notNull(), plateNumber: text('plate_number').notNull(), vin: text('vin'), fuelType: fuelTypeEnum('fuel_type').notNull(), mileageKm: integer('mileage_km').default(0).notNull(), status: text('status').default('AVAILABLE').notNull(), nextServiceDate: date('next_service_date'), insuranceExpiresAt: date('insurance_expires_at'), registrationExpiresAt: date('registration_expires_at'), telemetryProvider: text('telemetry_provider'), ...timestamps }, (table) => [uniqueIndex('vehicles_code_idx').on(table.vehicleCode), uniqueIndex('vehicles_plate_idx').on(table.plateNumber), index('vehicles_status_city_idx').on(table.status,table.cityId)])

export const driverStatusEnum = pgEnum('driver_status', ['offline','available','assigned','arriving','arrived','on_trip','paused','unavailable'])
export const driverProfiles = pgTable('driver_profiles', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), licenceNumber: text('licence_number'), licenceExpiry: date('licence_expiry'), licenceClass: text('licence_class'), yearsExperience: integer('years_experience').default(0).notNull(), rating: numeric('rating',{precision:3,scale:2}).default('0').notNull(), completedTrips: integer('completed_trips').default(0).notNull(), trainingStatus: text('training_status').default('PENDING').notNull(), chauffeurStatus: text('chauffeur_status').default('INACTIVE').notNull(), driverLevelCode: text('driver_level_code').default('STARTER').notNull(), availabilityStatus: driverStatusEnum('availability_status').default('offline').notNull(), currentVehicleId: uuid('current_vehicle_id'), acceptanceRate: numeric('acceptance_rate',{precision:5,scale:2}).default('0').notNull(), completionRate: numeric('completion_rate',{precision:5,scale:2}).default('0').notNull(), safetyScore: numeric('safety_score',{precision:5,scale:2}).default('0').notNull(), performanceScore: numeric('performance_score',{precision:5,scale:2}).default('0').notNull(), contractStatus: text('contract_status').default('PENDING').notNull(), emergencyInfo: jsonb('emergency_info').default({}).notNull(), experience: jsonb('experience').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('driver_profiles_user_idx').on(table.userId), index('drivers_status_idx').on(table.chauffeurStatus), index('drivers_availability_idx').on(table.availabilityStatus)])
export const vehicleAssignments = pgTable('vehicle_assignments', { id: uuid('id').defaultRandom().primaryKey(), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), assignedBy: uuid('assigned_by').references(() => users.id), startsAt: timestamp('starts_at',{withTimezone:true}).notNull(), endsAt: timestamp('ends_at',{withTimezone:true}), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [index('assignments_vehicle_active_idx').on(table.vehicleId,table.active), index('assignments_driver_active_idx').on(table.driverId,table.active)])

export const membershipPlans = pgTable('membership_plans', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), description: text('description').default('').notNull(), monthlyPrice: numeric('monthly_price',{precision:14,scale:2}), annualPrice: numeric('annual_price',{precision:14,scale:2}), trialPrice: numeric('trial_price',{precision:14,scale:2}), trialDays: integer('trial_days').default(0).notNull(), gracePeriodDays: integer('grace_period_days').default(0).notNull(), active: boolean('active').default(true).notNull(), displayOrder: integer('display_order').default(0).notNull(), ...timestamps }, (table) => [uniqueIndex('membership_plans_code_idx').on(table.code)])
export const membershipBenefits = pgTable('membership_benefits', { id: uuid('id').defaultRandom().primaryKey(), planId: uuid('plan_id').notNull().references(() => membershipPlans.id,{onDelete:'cascade'}), benefitKey: text('benefit_key').notNull(), label: text('label').notNull(), value: jsonb('value').notNull(), limits: jsonb('limits').default({}).notNull(), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('membership_benefit_key_idx').on(table.planId,table.benefitKey)])
export const subscriptions = pgTable('subscriptions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), planId: uuid('plan_id').notNull().references(() => membershipPlans.id), status: text('status').default('PENDING').notNull(), billingCycle: text('billing_cycle').default('MONTHLY').notNull(), startsAt: timestamp('starts_at',{withTimezone:true}), renewsAt: timestamp('renews_at',{withTimezone:true}), expiresAt: timestamp('expires_at',{withTimezone:true}), cancelledAt: timestamp('cancelled_at',{withTimezone:true}), paymentProvider: text('payment_provider'), providerReference: text('provider_reference'), benefitSnapshot: jsonb('benefit_snapshot').default({}).notNull(), ...timestamps }, (table) => [index('subscriptions_user_status_idx').on(table.userId,table.status)])

export const corporateAccounts = pgTable('corporate_accounts', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), registrationNumber: text('registration_number'), billingEmail: text('billing_email').notNull(), billingType: text('billing_type').default('PREPAID').notNull(), creditLimit: numeric('credit_limit',{precision:14,scale:2}), monthlySpendLimit: numeric('monthly_spend_limit',{precision:14,scale:2}), status: text('status').default('PENDING').notNull(), settings: jsonb('settings').default({}).notNull(), ...timestamps })
export const departments = pgTable('departments', { id: uuid('id').defaultRandom().primaryKey(), corporateAccountId: uuid('corporate_account_id').notNull().references(() => corporateAccounts.id), name: text('name').notNull(), monthlyLimit: numeric('monthly_limit',{precision:14,scale:2}), ...timestamps })
export const corporateMembers = pgTable('corporate_members', { id: uuid('id').defaultRandom().primaryKey(), corporateAccountId: uuid('corporate_account_id').notNull().references(() => corporateAccounts.id), userId: uuid('user_id').notNull().references(() => users.id), departmentId: uuid('department_id').references(() => departments.id), authorisationLevel: text('authorisation_level').default('RIDER').notNull(), rideLimit: numeric('ride_limit',{precision:14,scale:2}), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('corporate_member_idx').on(table.corporateAccountId,table.userId)])
export const corporateContracts = pgTable('corporate_contracts', { id: uuid('id').defaultRandom().primaryKey(), corporateAccountId: uuid('corporate_account_id').notNull().references(() => corporateAccounts.id), startsOn: date('starts_on').notNull(), endsOn: date('ends_on'), pricingModel: text('pricing_model').notNull(), paymentTerms: text('payment_terms'), approvedVehicleClasses: jsonb('approved_vehicle_classes').default([]).notNull(), creditLimit: numeric('credit_limit',{precision:14,scale:2}), monthlySpendLimit: numeric('monthly_spend_limit',{precision:14,scale:2}), approvalRules: jsonb('approval_rules').default({}).notNull(), includedServices: jsonb('included_services').default([]).notNull(), specialRates: jsonb('special_rates').default({}).notNull(), notes: text('notes'), status: text('status').default('DRAFT').notNull(), ...timestamps })

export const routes = pgTable('routes', { id: uuid('id').defaultRandom().primaryKey(), originCityId: uuid('origin_city_id').notNull().references(() => cities.id), destinationCityId: uuid('destination_city_id').notNull().references(() => cities.id), distanceKm: numeric('distance_km',{precision:10,scale:2}), estimatedMinutes: integer('estimated_minutes'), vehicleClassIds: jsonb('vehicle_class_ids').default([]).notNull(), priceRules: jsonb('price_rules').default({}).notNull(), operatingDays: jsonb('operating_days').default([]).notNull(), restrictions: jsonb('restrictions').default({}).notNull(), active: boolean('active').default(false).notNull(), ...timestamps })
export const bookings = pgTable('bookings', { id: uuid('id').defaultRandom().primaryKey(), reference: text('reference').notNull(), bookerId: uuid('booker_id').notNull().references(() => users.id), corporateAccountId: uuid('corporate_account_id').references(() => corporateAccounts.id), cityId: uuid('city_id').notNull().references(() => cities.id), vehicleClassId: uuid('vehicle_class_id').references(() => vehicleClasses.id), serviceType: text('service_type'), bookingRelationship: text('booking_relationship').default('SELF').notNull(), tripType: text('trip_type').notNull(), status: bookingStatusEnum('status').default('DRAFT').notNull(), pickup: jsonb('pickup').notNull(), destination: jsonb('destination').notNull(), scheduledAt: timestamp('scheduled_at',{withTimezone:true}), passengerCount: integer('passenger_count').default(1).notNull(), luggage: jsonb('luggage').default({}).notNull(), specialInstructions: text('special_instructions'), sharedRideEligible: boolean('shared_ride_eligible').default(false).notNull(), estimate: jsonb('estimate').default({}).notNull(), routeSnapshot: jsonb('route_snapshot').default({}).notNull(), fareSnapshot: jsonb('fare_snapshot').default({}).notNull(), membershipDiscount: numeric('membership_discount',{precision:14,scale:2}).default('0').notNull(), cancellationReason: text('cancellation_reason'), cancelledAt: timestamp('cancelled_at',{withTimezone:true}), cancellationRuleSnapshot: jsonb('cancellation_rule_snapshot').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('bookings_reference_idx').on(table.reference), index('bookings_user_status_idx').on(table.bookerId,table.status), index('bookings_city_schedule_idx').on(table.cityId,table.scheduledAt)])
export const bookingPassengers = pgTable('booking_passengers', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id,{onDelete:'cascade'}), userId: uuid('user_id').references(() => users.id), fullName: text('full_name').notNull(), phone: text('phone').notNull(), email: text('email'), isBooker: boolean('is_booker').default(false).notNull(), specialInstructions: text('special_instructions'), ...timestamps })
export const trips = pgTable('trips', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id), driverId: uuid('driver_id').references(() => driverProfiles.id), vehicleId: uuid('vehicle_id').references(() => vehicles.id), status: bookingStatusEnum('status').default('CONFIRMED').notNull(), startedAt: timestamp('started_at',{withTimezone:true}), completedAt: timestamp('completed_at',{withTimezone:true}), actualDistanceKm: numeric('actual_distance_km',{precision:10,scale:2}), actualDurationMinutes: integer('actual_duration_minutes'), fareSnapshot: jsonb('fare_snapshot').default({}).notNull(), notes: text('notes'), ...timestamps }, (table) => [index('trips_status_idx').on(table.status), index('trips_driver_idx').on(table.driverId)])
export const tripPassengers = pgTable('trip_passengers', { id: uuid('id').defaultRandom().primaryKey(), tripId: uuid('trip_id').notNull().references(() => trips.id,{onDelete:'cascade'}), bookingPassengerId: uuid('booking_passenger_id').references(() => bookingPassengers.id), pickupSequence: integer('pickup_sequence'), dropoffSequence: integer('dropoff_sequence'), passengerVerification: text('passenger_verification'), ...timestamps })
export const tripLocations = pgTable('trip_locations', { id: uuid('id').defaultRandom().primaryKey(), tripId: uuid('trip_id').notNull().references(() => trips.id,{onDelete:'cascade'}), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), latitude: numeric('latitude',{precision:10,scale:7}).notNull(), longitude: numeric('longitude',{precision:10,scale:7}).notNull(), accuracyMeters: numeric('accuracy_meters',{precision:8,scale:2}), recordedAt: timestamp('recorded_at',{withTimezone:true}).defaultNow().notNull() }, (table) => [index('trip_locations_trip_time_idx').on(table.tripId,table.recordedAt)])

export const sharedRides = pgTable('shared_rides', { id: uuid('id').defaultRandom().primaryKey(), cityId: uuid('city_id').notNull().references(() => cities.id), vehicleClassId: uuid('vehicle_class_id').notNull().references(() => vehicleClasses.id), tripId: uuid('trip_id').references(() => trips.id), status: sharedStatusEnum('status').default('MATCHING').notNull(), maxPassengers: integer('max_passengers').default(4).notNull(), pickupZoneId: uuid('pickup_zone_id').references(() => operatingZones.id), dropoffZoneId: uuid('dropoff_zone_id').references(() => operatingZones.id), routeData: jsonb('route_data').default({}).notNull(), rulesSnapshot: jsonb('rules_snapshot').default({}).notNull(), ...timestamps }, (table) => [index('shared_rides_matching_idx').on(table.cityId,table.status,table.vehicleClassId)])
export const sharedRideParticipants = pgTable('shared_ride_participants', { id: uuid('id').defaultRandom().primaryKey(), sharedRideId: uuid('shared_ride_id').notNull().references(() => sharedRides.id,{onDelete:'cascade'}), userId: uuid('user_id').notNull().references(() => users.id), bookingId: uuid('booking_id').references(() => bookings.id), status: sharedStatusEnum('status').default('AVAILABLE').notNull(), seats: integer('seats').default(1).notNull(), pickup: jsonb('pickup').notNull(), destination: jsonb('destination').notNull(), availableAt: timestamp('available_at',{withTimezone:true}).defaultNow().notNull(), ...timestamps }, (table) => [index('shared_participant_status_idx').on(table.status,table.availableAt)])

export const pricingRules = pgTable('pricing_rules', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), priority: integer('priority').default(100).notNull(), cityId: uuid('city_id').references(() => cities.id), vehicleClassId: uuid('vehicle_class_id').references(() => vehicleClasses.id), serviceType: text('service_type'), pricingType: text('pricing_type').notNull(), conditions: jsonb('conditions').default({}).notNull(), calculation: jsonb('calculation').notNull(), activeFrom: timestamp('active_from',{withTimezone:true}), activeUntil: timestamp('active_until',{withTimezone:true}), active: boolean('active').default(true).notNull(), version: integer('version').default(1).notNull(), ...timestamps }, (table) => [index('pricing_rules_lookup_idx').on(table.active,table.cityId,table.vehicleClassId,table.priority)])
export const pricingZones = pgTable('pricing_zones', { id: uuid('id').defaultRandom().primaryKey(), cityId: uuid('city_id').notNull().references(() => cities.id), name: text('name').notNull(), geometry: jsonb('geometry').notNull(), surcharge: numeric('surcharge',{precision:14,scale:2}), active: boolean('active').default(true).notNull(), ...timestamps })

export const wallets = pgTable('wallets', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), cashBalance: numeric('cash_balance',{precision:14,scale:2}).default('0').notNull(), promotionalBalance: numeric('promotional_balance',{precision:14,scale:2}).default('0').notNull(), membershipCreditBalance: numeric('membership_credit_balance',{precision:14,scale:2}).default('0').notNull(), rewardCreditBalance: numeric('reward_credit_balance',{precision:14,scale:2}).default('0').notNull(), currency: text('currency').default('NGN').notNull(), ...timestamps }, (table) => [uniqueIndex('wallets_user_idx').on(table.userId)])
export const walletTransactions = pgTable('wallet_transactions', { id: uuid('id').defaultRandom().primaryKey(), walletId: uuid('wallet_id').notNull().references(() => wallets.id), balanceType: text('balance_type').notNull(), transactionType: text('transaction_type').notNull(), amount: numeric('amount',{precision:14,scale:2}).notNull(), reference: text('reference').notNull(), status: text('status').default('PENDING').notNull(), metadata: jsonb('metadata').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('wallet_transaction_reference_idx').on(table.reference)])
export const payments = pgTable('payments', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), bookingId: uuid('booking_id').references(() => bookings.id), amount: numeric('amount',{precision:14,scale:2}).notNull(), currency: text('currency').default('NGN').notNull(), provider: text('provider').notNull(), providerReference: text('provider_reference').notNull(), status: paymentStatusEnum('status').default('PENDING').notNull(), paymentMethod: text('payment_method'), verifiedAt: timestamp('verified_at',{withTimezone:true}), rawResponse: jsonb('raw_response').default({}).notNull(), ...timestamps }, (table) => [uniqueIndex('payments_provider_reference_idx').on(table.provider,table.providerReference)])
export const paymentTransactions = pgTable('payment_transactions', { id: uuid('id').defaultRandom().primaryKey(), paymentId: uuid('payment_id').notNull().references(() => payments.id), eventType: text('event_type').notNull(), providerEventId: text('provider_event_id'), signatureVerified: boolean('signature_verified').default(false).notNull(), payload: jsonb('payload').notNull(), ...timestamps })

export const rewardAccounts = pgTable('reward_accounts', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), pointsBalance: integer('points_balance').default(0).notNull(), ...timestamps }, (table) => [uniqueIndex('reward_accounts_user_idx').on(table.userId)])
export const rewards = pgTable('rewards', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), rewardType: text('reward_type').notNull(), pointsCost: integer('points_cost').notNull(), value: jsonb('value').notNull(), membershipEligibility: jsonb('membership_eligibility').default([]).notNull(), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('rewards_code_idx').on(table.code)])
export const rewardTransactions = pgTable('reward_transactions', { id: uuid('id').defaultRandom().primaryKey(), rewardAccountId: uuid('reward_account_id').notNull().references(() => rewardAccounts.id), transactionType: text('transaction_type').notNull(), points: integer('points').notNull(), ruleKey: text('rule_key').notNull(), expiresAt: timestamp('expires_at',{withTimezone:true}), metadata: jsonb('metadata').default({}).notNull(), ...timestamps })
export const referrals = pgTable('referrals', { id: uuid('id').defaultRandom().primaryKey(), referrerId: uuid('referrer_id').notNull().references(() => users.id), referredUserId: uuid('referred_user_id').references(() => users.id), code: text('code').notNull(), status: text('status').default('PENDING').notNull(), qualifyingTransactionId: uuid('qualifying_transaction_id'), fraudSignals: jsonb('fraud_signals').default([]).notNull(), rewardData: jsonb('reward_data').default({}).notNull(), expiresAt: timestamp('expires_at',{withTimezone:true}), ...timestamps }, (table) => [uniqueIndex('referral_code_idx').on(table.code)])

export const recurringBookings = pgTable('recurring_bookings', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), corporateAccountId: uuid('corporate_account_id').references(() => corporateAccounts.id), recurrenceRule: jsonb('recurrence_rule').notNull(), bookingTemplate: jsonb('booking_template').notNull(), nextRunAt: timestamp('next_run_at',{withTimezone:true}), active: boolean('active').default(true).notNull(), status: text('status').default('ACTIVE').notNull(), ...timestamps })
export const airportTransfers = pgTable('airport_transfers', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id), airportCode: text('airport_code').notNull(), flightNumber: text('flight_number'), direction: text('direction').notNull(), meetAndGreet: boolean('meet_and_greet').default(false).notNull(), luggage: jsonb('luggage').default({}).notNull(), waitingRequirement: text('waiting_requirement'), flightStatusSnapshot: jsonb('flight_status_snapshot'), notes: text('notes'), flightProviderReference: text('flight_provider_reference'), ...timestamps })
export const events = pgTable('events', { id: uuid('id').defaultRandom().primaryKey(), corporateAccountId: uuid('corporate_account_id').references(() => corporateAccounts.id), clientUserId: uuid('client_user_id').references(() => users.id), name: text('name').notNull(), eventType: text('event_type').notNull(), location: jsonb('location'), startsAt: timestamp('starts_at',{withTimezone:true}).notNull(), endsAt: timestamp('ends_at',{withTimezone:true}), guestCount: integer('guest_count'), vehiclesRequired: integer('vehicles_required'), chauffeursRequired: integer('chauffeurs_required'), itinerary: jsonb('itinerary').default([]).notNull(), venue: jsonb('venue').notNull(), operationsNotes: text('operations_notes'), status: text('status').default('PLANNING').notNull(), ...timestamps })
export const eventVehicles = pgTable('event_vehicles', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id,{onDelete:'cascade'}), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), driverId: uuid('driver_id').references(() => driverProfiles.id), assignment: jsonb('assignment').default({}).notNull(), status: text('status').default('PLANNED').notNull(), ...timestamps })
export const eventPassengers = pgTable('event_passengers', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id,{onDelete:'cascade'}), fullName: text('full_name').notNull(), phone: text('phone'), pickup: jsonb('pickup'), assignedVehicleId: uuid('assigned_vehicle_id').references(() => vehicles.id), notes: text('notes'), ...timestamps })
export const incidents = pgTable('incidents', { id: uuid('id').defaultRandom().primaryKey(), reporterId: uuid('reporter_id').notNull().references(() => users.id), tripId: uuid('trip_id').references(() => trips.id), vehicleId: uuid('vehicle_id').references(() => vehicles.id), driverId: uuid('driver_id').references(() => driverProfiles.id), incidentType: text('incident_type').notNull(), priority: text('priority').default('MEDIUM').notNull(), details: text('details').notNull(), location: jsonb('location'), status: text('status').default('OPEN').notNull(), workflowSnapshot: jsonb('workflow_snapshot').default({}).notNull(), ...timestamps }, (table) => [index('incidents_status_priority_idx').on(table.status,table.priority)])
export const emergencyContacts = pgTable('emergency_contacts', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), name: text('name').notNull(), phone: text('phone').notNull(), relationship: text('relationship'), primary: boolean('primary').default(false).notNull(), ...timestamps })
export const supportTickets = pgTable('support_tickets', { id: uuid('id').defaultRandom().primaryKey(), reference: text('reference').notNull(), userId: uuid('user_id').notNull().references(() => users.id), category: text('category').notNull(), priority: text('priority').default('NORMAL').notNull(), status: text('status').default('OPEN').notNull(), assignedAgentId: uuid('assigned_agent_id').references(() => users.id), conversation: jsonb('conversation').default([]).notNull(), resolution: text('resolution'), ...timestamps }, (table) => [uniqueIndex('support_ticket_reference_idx').on(table.reference)])
export const notifications = pgTable('notifications', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), channel: text('channel').notNull(), templateKey: text('template_key').notNull(), subject: text('subject'), content: jsonb('content').notNull(), status: text('status').default('QUEUED').notNull(), sentAt: timestamp('sent_at',{withTimezone:true}), ...timestamps })
export const documents = pgTable('documents', { id: uuid('id').defaultRandom().primaryKey(), ownerType: text('owner_type').notNull(), ownerId: uuid('owner_id').notNull(), documentType: text('document_type').notNull(), storageKey: text('storage_key').notNull(), expiresAt: date('expires_at'), verificationStatus: text('verification_status').default('PENDING').notNull(), reviewedBy: uuid('reviewed_by').references(() => users.id), notes: text('notes'), ...timestamps }, (table) => [index('documents_owner_idx').on(table.ownerType,table.ownerId)])
export const maintenanceRecords = pgTable('maintenance_records', { id: uuid('id').defaultRandom().primaryKey(), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), recordType: text('record_type').notNull(), serviceDate: date('service_date').notNull(), mileageKm: integer('mileage_km'), cost: numeric('cost',{precision:14,scale:2}), provider: text('provider'), notes: text('notes'), nextServiceDate: date('next_service_date'), ...timestamps })
export const fuelRecords = pgTable('fuel_records', { id: uuid('id').defaultRandom().primaryKey(), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), litres: numeric('litres',{precision:10,scale:2}).notNull(), cost: numeric('cost',{precision:14,scale:2}).notNull(), mileageKm: integer('mileage_km'), recordedAt: timestamp('recorded_at',{withTimezone:true}).defaultNow().notNull(), ...timestamps })
export const chargingRecords = pgTable('charging_records', { id: uuid('id').defaultRandom().primaryKey(), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), energyKwh: numeric('energy_kwh',{precision:10,scale:2}).notNull(), cost: numeric('cost',{precision:14,scale:2}).notNull(), chargingLocation: text('charging_location'), startedAt: timestamp('started_at',{withTimezone:true}), endedAt: timestamp('ended_at',{withTimezone:true}), providerData: jsonb('provider_data').default({}).notNull(), ...timestamps })
export const auditLogs = pgTable('audit_logs', { id: uuid('id').defaultRandom().primaryKey(), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), targetType: text('target_type').notNull(), targetId: text('target_id').notNull(), before: jsonb('before'), after: jsonb('after'), ipAddress: text('ip_address'), deviceData: jsonb('device_data').default({}).notNull(), createdAt: timestamp('created_at',{withTimezone:true}).defaultNow().notNull() }, (table) => [index('audit_target_idx').on(table.targetType,table.targetId), index('audit_actor_time_idx').on(table.actorId,table.createdAt)])
export const savedLocations = pgTable('saved_locations', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), label: text('label').notNull(), address: text('address').notNull(), location: jsonb('location').notNull(), ...timestamps })
export const favouriteChauffeurs = pgTable('favourite_chauffeurs', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), ...timestamps }, (table) => [uniqueIndex('favourite_chauffeur_idx').on(table.userId,table.driverId)])
export const favouriteVehicles = pgTable('favourite_vehicles', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), vehicleId: uuid('vehicle_id').notNull().references(() => vehicles.id), ...timestamps }, (table) => [uniqueIndex('favourite_vehicle_idx').on(table.userId,table.vehicleId)])
export const coupons = pgTable('coupons', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), discountType: text('discount_type').notNull(), value: numeric('value',{precision:14,scale:2}).notNull(), conditions: jsonb('conditions').default({}).notNull(), startsAt: timestamp('starts_at',{withTimezone:true}), endsAt: timestamp('ends_at',{withTimezone:true}), usageLimit: integer('usage_limit'), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('coupon_code_idx').on(table.code)])
export const promotions = pgTable('promotions', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), promotionType: text('promotion_type').notNull(), rules: jsonb('rules').notNull(), startsAt: timestamp('starts_at',{withTimezone:true}), endsAt: timestamp('ends_at',{withTimezone:true}), active: boolean('active').default(true).notNull(), ...timestamps })
export const invoices = pgTable('invoices', { id: uuid('id').defaultRandom().primaryKey(), invoiceNumber: text('invoice_number').notNull(), corporateAccountId: uuid('corporate_account_id').notNull().references(() => corporateAccounts.id), periodStart: date('period_start').notNull(), periodEnd: date('period_end').notNull(), subtotal: numeric('subtotal',{precision:14,scale:2}).notNull(), discounts: numeric('discounts',{precision:14,scale:2}).default('0').notNull(), taxesAndFees: numeric('taxes_and_fees',{precision:14,scale:2}).default('0').notNull(), total: numeric('total',{precision:14,scale:2}).notNull(), dueDate: date('due_date').notNull(), status: text('status').default('DRAFT').notNull(), ...timestamps }, (table) => [uniqueIndex('invoice_number_idx').on(table.invoiceNumber)])
export const invoiceItems = pgTable('invoice_items', { id: uuid('id').defaultRandom().primaryKey(), invoiceId: uuid('invoice_id').notNull().references(() => invoices.id,{onDelete:'cascade'}), bookingId: uuid('booking_id').references(() => bookings.id), description: text('description').notNull(), quantity: integer('quantity').default(1).notNull(), unitAmount: numeric('unit_amount',{precision:14,scale:2}).notNull(), total: numeric('total',{precision:14,scale:2}).notNull(), ...timestamps })

export const services = pgTable('services', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), description: text('description').default('').notNull(), requiresRoute: boolean('requires_route').default(false).notNull(), allowSharedRide: boolean('allow_shared_ride').default(false).notNull(), requiresScheduledTime: boolean('requires_scheduled_time').default(false).notNull(), active: boolean('active').default(true).notNull(), displayOrder: integer('display_order').default(0).notNull(), ...timestamps }, (table) => [uniqueIndex('services_code_idx').on(table.code)])
export const airports = pgTable('airports', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), cityId: uuid('city_id').references(() => cities.id), meetingPoints: jsonb('meeting_points').default({}).notNull(), active: boolean('active').default(false).notNull(), ...timestamps }, (table) => [uniqueIndex('airports_code_idx').on(table.code)])

export const driverLevels = pgTable('driver_levels', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), displayOrder: integer('display_order').default(0).notNull(), requirements: jsonb('requirements').default({}).notNull(), benefits: jsonb('benefits').default([]).notNull(), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('driver_levels_code_idx').on(table.code)])
export const driverAssignments = pgTable('driver_assignments', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id), tripId: uuid('trip_id').references(() => trips.id), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), status: text('status').default('OFFERED').notNull(), offeredAt: timestamp('offered_at',{withTimezone:true}).defaultNow().notNull(), respondedAt: timestamp('responded_at',{withTimezone:true}), expiresAt: timestamp('expires_at',{withTimezone:true}), declineReason: text('decline_reason'), notes: text('notes'), ...timestamps }, (table) => [index('driver_assignments_driver_idx').on(table.driverId,table.status)])
export const driverAvailability = pgTable('driver_availability', { id: uuid('id').defaultRandom().primaryKey(), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), status: driverStatusEnum('status').notNull(), startedAt: timestamp('started_at',{withTimezone:true}).defaultNow().notNull(), endedAt: timestamp('ended_at',{withTimezone:true}), ...timestamps }, (table) => [index('driver_availability_driver_idx').on(table.driverId,table.startedAt)])
export const driverEarningsRecords = pgTable('driver_earnings_records', { id: uuid('id').defaultRandom().primaryKey(), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), periodStart: date('period_start').notNull(), periodEnd: date('period_end').notNull(), tripEarnings: numeric('trip_earnings',{precision:14,scale:2}).default('0').notNull(), activeHourEarnings: numeric('active_hour_earnings',{precision:14,scale:2}).default('0').notNull(), productivityBonus: numeric('productivity_bonus',{precision:14,scale:2}).default('0').notNull(), performanceBonus: numeric('performance_bonus',{precision:14,scale:2}).default('0').notNull(), qualityBonus: numeric('quality_bonus',{precision:14,scale:2}).default('0').notNull(), specialAssignmentBonus: numeric('special_assignment_bonus',{precision:14,scale:2}).default('0').notNull(), deductions: numeric('deductions',{precision:14,scale:2}).default('0').notNull(), grossEarnings: numeric('gross_earnings',{precision:14,scale:2}).default('0').notNull(), netEarnings: numeric('net_earnings',{precision:14,scale:2}).default('0').notNull(), qualifyingActiveMinutes: integer('qualifying_active_minutes').default(0).notNull(), status: text('status').default('OPEN').notNull(), ...timestamps }, (table) => [uniqueIndex('driver_earnings_period_idx').on(table.driverId,table.periodStart,table.periodEnd)])
export const driverPerformanceRecords = pgTable('driver_performance_records', { id: uuid('id').defaultRandom().primaryKey(), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id), periodStart: date('period_start').notNull(), periodEnd: date('period_end').notNull(), punctuality: numeric('punctuality',{precision:5,scale:2}).default('0').notNull(), acceptanceCompletion: numeric('acceptance_completion',{precision:5,scale:2}).default('0').notNull(), ratingScore: numeric('rating_score',{precision:5,scale:2}).default('0').notNull(), safety: numeric('safety',{precision:5,scale:2}).default('0').notNull(), utilisation: numeric('utilisation',{precision:5,scale:2}).default('0').notNull(), vehicleCare: numeric('vehicle_care',{precision:5,scale:2}).default('0').notNull(), complaints: numeric('complaints',{precision:5,scale:2}).default('0').notNull(), weightedScore: numeric('weighted_score',{precision:5,scale:2}).default('0').notNull(), assignmentsOffered: integer('assignments_offered').default(0).notNull(), assignmentsAccepted: integer('assignments_accepted').default(0).notNull(), assignmentsDeclined: integer('assignments_declined').default(0).notNull(), weightsSnapshot: jsonb('weights_snapshot').default({}).notNull(), status: text('status').default('OPEN').notNull(), ...timestamps }, (table) => [uniqueIndex('driver_performance_period_idx').on(table.driverId,table.periodStart,table.periodEnd)])
export const declineReasons = pgTable('decline_reasons', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), label: text('label').notNull(), legitimate: boolean('legitimate').default(true).notNull(), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('decline_reasons_code_idx').on(table.code)])

export const signupResponses = pgTable('signup_responses', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), audienceType: text('audience_type').notNull(), questionKey: text('question_key').notNull(), selectedOption: text('selected_option'), otherText: text('other_text'), submittedAt: timestamp('submitted_at',{withTimezone:true}).defaultNow().notNull(), ...timestamps }, (table) => [index('signup_responses_audience_idx').on(table.audienceType,table.questionKey), index('signup_responses_user_idx').on(table.userId)])

export const routinePackages = pgTable('routine_packages', { id: uuid('id').defaultRandom().primaryKey(), code: text('code').notNull(), name: text('name').notNull(), rideCount: integer('ride_count'), validityDays: integer('validity_days'), audienceType: text('audience_type').default('INDIVIDUAL').notNull(), discountPercent: numeric('discount_percent',{precision:5,scale:2}), packagePrice: numeric('package_price',{precision:14,scale:2}), eligibility: jsonb('eligibility').default({}).notNull(), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('routine_packages_code_idx').on(table.code)])
export const routineSubscriptions = pgTable('routine_subscriptions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id), packageId: uuid('package_id').references(() => routinePackages.id), corporateAccountId: uuid('corporate_account_id').references(() => corporateAccounts.id), origin: jsonb('origin').notNull(), destination: jsonb('destination').notNull(), days: jsonb('days').default([]).notNull(), pickupTime: text('pickup_time'), returnTime: text('return_time'), passengers: integer('passengers').default(1).notNull(), vehicleClassId: uuid('vehicle_class_id'), serviceType: text('service_type'), startDate: date('start_date'), endDate: date('end_date'), status: text('status').default('ACTIVE').notNull(), remainingRides: integer('remaining_rides'), routeEstimate: jsonb('route_estimate').default({}).notNull(), ...timestamps }, (table) => [index('routine_subscriptions_user_idx').on(table.userId,table.status)])
export const routineRides = pgTable('routine_rides', { id: uuid('id').defaultRandom().primaryKey(), routineSubscriptionId: uuid('routine_subscription_id').notNull().references(() => routineSubscriptions.id,{onDelete:'cascade'}), bookingId: uuid('booking_id').references(() => bookings.id), scheduledFor: timestamp('scheduled_for',{withTimezone:true}).notNull(), direction: text('direction').default('OUTBOUND').notNull(), status: text('status').default('PLANNED').notNull(), ...timestamps }, (table) => [index('routine_rides_sub_idx').on(table.routineSubscriptionId,table.scheduledFor)])

export const corporatePolicies = pgTable('corporate_policies', { id: uuid('id').defaultRandom().primaryKey(), corporateAccountId: uuid('corporate_account_id').notNull().references(() => corporateAccounts.id), name: text('name').notNull(), allowedVehicleClasses: jsonb('allowed_vehicle_classes').default([]).notNull(), allowedServices: jsonb('allowed_services').default([]).notNull(), perTripSpendLimit: numeric('per_trip_spend_limit',{precision:14,scale:2}), monthlyTripLimit: integer('monthly_trip_limit'), monthlySpendLimit: numeric('monthly_spend_limit',{precision:14,scale:2}), bookingPermissions: jsonb('booking_permissions').default({}).notNull(), approvalLevel: text('approval_level').default('NONE').notNull(), maxAdvanceDays: integer('max_advance_days'), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [index('corporate_policies_account_idx').on(table.corporateAccountId,table.active)])
export const eventItineraryItems = pgTable('event_itinerary_items', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id,{onDelete:'cascade'}), sequence: integer('sequence').default(0).notNull(), time: timestamp('time',{withTimezone:true}), title: text('title').notNull(), pickup: jsonb('pickup'), destination: jsonb('destination'), vehicleId: uuid('vehicle_id').references(() => vehicles.id), driverId: uuid('driver_id').references(() => driverProfiles.id), status: text('status').default('PLANNED').notNull(), ...timestamps }, (table) => [index('event_itinerary_event_idx').on(table.eventId,table.sequence)])
export const interstateDepartures = pgTable('interstate_departures', { id: uuid('id').defaultRandom().primaryKey(), routeId: uuid('route_id').notNull().references(() => routes.id), departureTime: timestamp('departure_time',{withTimezone:true}).notNull(), vehicleClassId: uuid('vehicle_class_id').references(() => vehicleClasses.id), vehicleId: uuid('vehicle_id').references(() => vehicles.id), driverId: uuid('driver_id').references(() => driverProfiles.id), fare: numeric('fare',{precision:14,scale:2}), seatsTotal: integer('seats_total').default(4).notNull(), seatsBooked: integer('seats_booked').default(0).notNull(), status: text('status').default('SCHEDULED').notNull(), ...timestamps }, (table) => [index('interstate_departures_route_idx').on(table.routeId,table.departureTime)])
export const feedback = pgTable('feedback', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), driverId: uuid('driver_id').references(() => driverProfiles.id), bookingId: uuid('booking_id').references(() => bookings.id), tripId: uuid('trip_id').references(() => trips.id), kind: text('kind').default('TRIP_RATING').notNull(), rating: integer('rating'), categories: jsonb('categories').default({}).notNull(), comment: text('comment'), npsScore: integer('nps_score'), status: text('status').default('UNRESOLVED').notNull(), resolvedAt: timestamp('resolved_at',{withTimezone:true}), ...timestamps }, (table) => [index('feedback_kind_idx').on(table.kind,table.status), index('feedback_booking_idx').on(table.bookingId)])
export const notificationIntents = pgTable('notification_intents', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id'), channel: text('channel').notNull(), templateKey: text('template_key').notNull(), recipient: text('recipient'), subject: text('subject'), payload: jsonb('payload').default({}).notNull(), bookingId: uuid('booking_id').references(() => bookings.id), status: text('status').default('INTENT_RECORDED').notNull(), provider: text('provider'), providerMessageId: text('provider_message_id'), failureReason: text('failure_reason'), deliveredAt: timestamp('delivered_at',{withTimezone:true}), ...timestamps }, (table) => [index('notification_intents_user_idx').on(table.userId,table.status)])
export const loyaltyRules = pgTable('loyalty_rules', { id: uuid('id').defaultRandom().primaryKey(), ruleKey: text('rule_key').notNull(), name: text('name').notNull(), ruleType: text('rule_type').default('EARN').notNull(), points: integer('points').default(0).notNull(), conditions: jsonb('conditions').default({}).notNull(), tierMultipliers: jsonb('tier_multipliers').default({}).notNull(), expiryDays: integer('expiry_days'), active: boolean('active').default(true).notNull(), ...timestamps }, (table) => [uniqueIndex('loyalty_rules_key_idx').on(table.ruleKey)])
export const rewardRedemptions = pgTable('reward_redemptions', { id: uuid('id').defaultRandom().primaryKey(), rewardAccountId: uuid('reward_account_id').notNull().references(() => rewardAccounts.id), rewardId: uuid('reward_id').references(() => rewards.id), points: integer('points').notNull(), status: text('status').default('PENDING').notNull(), reference: text('reference'), ...timestamps })
export const referralRewards = pgTable('referral_rewards', { id: uuid('id').defaultRandom().primaryKey(), referralId: uuid('referral_id').notNull().references(() => referrals.id), userId: uuid('user_id').notNull().references(() => users.id), ruleKey: text('rule_key').notNull(), rewardType: text('reward_type').notNull(), status: text('status').default('PENDING').notNull(), qualifyingEvent: text('qualifying_event'), issuedAt: timestamp('issued_at',{withTimezone:true}), ...timestamps }, (table) => [index('referral_rewards_referral_idx').on(table.referralId)])
export const walletLedgerEntries = pgTable('wallet_ledger_entries', { id: uuid('id').defaultRandom().primaryKey(), walletId: uuid('wallet_id').notNull().references(() => wallets.id), entryType: text('entry_type').notNull(), balanceType: text('balance_type').notNull(), amount: numeric('amount',{precision:14,scale:2}).notNull(), runningBalance: numeric('running_balance',{precision:14,scale:2}), reason: text('reason').notNull(), bookingId: uuid('booking_id').references(() => bookings.id), paymentId: uuid('payment_id').references(() => payments.id), metadata: jsonb('metadata').default({}).notNull(), recordedAt: timestamp('recorded_at',{withTimezone:true}).defaultNow().notNull() }, (table) => [index('wallet_ledger_wallet_idx').on(table.walletId,table.recordedAt)])
export const bookingEvents = pgTable('booking_events', { id: uuid('id').defaultRandom().primaryKey(), bookingId: uuid('booking_id').notNull().references(() => bookings.id,{onDelete:'cascade'}), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), actorId: uuid('actor_id').references(() => users.id), note: text('note'), createdAt: timestamp('created_at',{withTimezone:true}).defaultNow().notNull() }, (table) => [index('booking_events_booking_idx').on(table.bookingId,table.createdAt)])
export const referralConfig = pgTable('referral_config', { id: uuid('id').defaultRandom().primaryKey(), qualifyingEvent: text('qualifying_event').notNull(), referrerRewardType: text('referrer_reward_type').notNull(), referrerRewardValue: jsonb('referrer_reward_value').default({}).notNull(), refereeRewardType: text('referee_reward_type'), refereeRewardValue: jsonb('referee_reward_value').default({}).notNull(), expiryDays: integer('expiry_days').default(90).notNull(), active: boolean('active').default(true).notNull(), ...timestamps })
export const sosAlerts = pgTable('sos_alerts', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), bookingId: uuid('booking_id').references(() => bookings.id), tripId: uuid('trip_id').references(() => trips.id), driverId: uuid('driver_id').references(() => driverProfiles.id), vehicleId: uuid('vehicle_id').references(() => vehicles.id), emergencyContactId: uuid('emergency_contact_id').references(() => emergencyContacts.id), coordinates: jsonb('coordinates'), locationAvailable: boolean('location_available').default(false).notNull(), details: text('details'), status: text('status').default('RAISED').notNull(), responseNotes: text('response_notes'), respondedBy: uuid('responded_by').references(() => users.id), respondedAt: timestamp('responded_at',{withTimezone:true}), ...timestamps }, (table) => [index('sos_alerts_status_idx').on(table.status,table.createdAt)])
export const appConfig = pgTable('app_config', { key: text('key').primaryKey(), value: jsonb('value').default({}).notNull(), description: text('description'), updatedBy: uuid('updated_by').references(() => users.id), ...timestamps })
