import { useState, type FormEvent } from 'react'
import { MapPin } from 'lucide-react'
import { AppShell } from './AppShell'
import { vehicleClasses } from '@/lib/domain'

export function BookingFlow() {
  const [message, setMessage] = useState('')
  function submit(event: FormEvent) { event.preventDefault(); setMessage('Your booking draft is ready. Connect maps and pricing integrations to calculate a live estimate before confirmation.') }
  return <AppShell kind="customer" title="Book a ride" subtitle="Fast, clear and controlled"><div className="booking-layout"><form className="booking-card" onSubmit={submit}><h2>Plan your journey</h2><p>Enter the trip details. FASTRIDES only presents operationally eligible options.</p><div className="form-grid"><div className="field full"><label htmlFor="pickup">Pickup</label><input id="pickup" required placeholder="Enter pickup location" /></div><div className="field full"><label htmlFor="destination">Destination</label><input id="destination" required placeholder="Enter destination" /></div><div className="field"><label htmlFor="trip-type">Trip type</label><select id="trip-type"><option>Immediate ride</option><option>Scheduled ride</option><option>Airport transfer</option><option>Round trip</option><option>Hourly chauffeur</option><option>Interstate</option><option>Event transportation</option></select></div><div className="field"><label htmlFor="city">Operating city</label><select id="city"><option>Abuja</option><option>Lagos</option></select></div><div className="field"><label htmlFor="date">Date</label><input id="date" type="date" /></div><div className="field"><label htmlFor="time">Time</label><input id="time" type="time" /></div><div className="field"><label htmlFor="passengers">Passengers</label><input id="passengers" type="number" min="1" max="14" defaultValue="1" /></div><div className="field"><label htmlFor="vehicle">Vehicle class</label><select id="vehicle">{vehicleClasses.map((vehicle) => <option key={vehicle.code}>{vehicle.name}</option>)}</select></div><div className="field full"><label htmlFor="instructions">Special instructions</label><textarea id="instructions" rows={3} placeholder="Luggage, accessibility or pickup notes" /></div></div>{message && <p className="notice" role="status">{message}</p>}<button className="button button-primary" type="submit" style={{marginTop:18}}>Check eligible options</button></form><aside className="booking-summary"><MapPin size={22}/><h3>Journey summary</h3><div className="summary-row"><span>Map route</span><strong>Not connected</strong></div><div className="summary-row"><span>Vehicle availability</span><strong>Pending lookup</strong></div><div className="summary-row"><span>Estimated duration</span><strong>Pending route</strong></div><div className="summary-total"><small>Estimated fare</small><strong>Calculated after route lookup</strong></div><p className="notice">An estimate is not presented as a guaranteed price unless a fixed pricing rule applies.</p></aside></div></AppShell>
}
