import { useState } from 'react'
import { Link } from '@tanstack/react-router'
import { AlertTriangle, ArrowRight, BatteryCharging, Building2, CalendarClock, CarFront, CircleDollarSign, Clock3, Fuel, Gauge, MapPin, Plane, ShieldCheck, Siren, Sparkles, TrendingUp, Users, WalletCards } from 'lucide-react'
import { AppShell } from './AppShell'

export function CustomerDashboard() {
  const [available, setAvailable] = useState(false)
  const [locationState, setLocationState] = useState('Not included in matching')
  function toggleAvailability() {
    if (available) { setAvailable(false); setLocationState('Not included in matching'); return }
    if (!navigator.geolocation) { setLocationState('Location is not supported on this device'); return }
    setLocationState('Requesting location permission…')
    navigator.geolocation.getCurrentPosition(() => { setAvailable(true); setLocationState('Permission granted · awaiting eligible zone and route lookup') },() => setLocationState('Location permission was not granted'),{enableHighAccuracy:true,maximumAge:15_000,timeout:10_000})
  }
  return <AppShell kind="customer" title="My mobility" subtitle="Tuesday, 8 September 2026">
    <div className="dashboard-hero"><section className="welcome-card"><p>Good morning, Amina</p><h2>Where can DTS take you today?</h2><p>Book now, schedule ahead or arrange a journey for someone else.</p><Link to="/app/book" className="button button-primary">Book a ride <ArrowRight size={16}/></Link></section><section className="membership-summary"><p className="overline">Current membership</p><h3>Dreamz Executive</h3><p>Renewal details are available when subscription billing is connected.</p><div className="credit-row"><span>Ride credits<strong>4 available</strong></span><span>Wallet<strong>₦0.00</strong></span></div></section></div>
    <div className="quick-grid">{[[CalendarClock,'Schedule ride','Plan ahead'],[Plane,'Airport transfer','Flight-ready flow'],[Users,'Book for someone','Family or guest'],[Sparkles,'Chauffeur service','By the hour']].map(([Icon,title,text]) => <Link to="/app/book" className="quick-card" key={String(title)}><Icon size={20}/><strong>{String(title)}</strong><small>{String(text)}</small></Link>)}</div>
    <div className="content-grid"><section className="panel"><div className="panel-head"><h3>Upcoming & recent</h3><Link to="/app/trips">View all</Link></div><div className="trip-row"><span className="trip-icon"><Plane size={16}/></span><div><strong>Airport transfer</strong><small>Wuse 2 → Nnamdi Azikiwe Airport · Demo</small></div><span>Scheduled</span></div><div className="trip-row"><span className="trip-icon"><CarFront size={16}/></span><div><strong>Premium sedan</strong><small>Maitama → Central Business District · Demo</small></div><span>Completed</span></div></section><section className="availability-panel"><Users size={22}/><h3>Availability Mode</h3><p>Join controlled shared-ride matching at supported pickup points. Location is used only with your permission while active.</p><div className="toggle-row"><span>{available ? 'Available for matching' : 'Currently off'}</span><button className={`switch ${available ? 'on' : ''}`} onClick={toggleAvailability} aria-label="Toggle Availability Mode" /></div><div className="integration-state"><MapPin size={13}/>{locationState}</div></section></div>
  </AppShell>
}

export function DriverDashboard() {
  const [online, setOnline] = useState(false)
  const [locationState, setLocationState] = useState('Location off')
  function requestLocation() {
    if (!navigator.geolocation) { setLocationState('Location unavailable'); return }
    setLocationState('Requesting permission…')
    navigator.geolocation.getCurrentPosition(() => setLocationState('Permission granted · updates wait for an authorised active trip'),() => setLocationState('Permission not granted'),{enableHighAccuracy:true,maximumAge:5_000,timeout:10_000})
  }
  return <AppShell kind="driver" title="Chauffeur workspace" subtitle="Simple, safe trip operations"><div className="dashboard-hero"><section className="welcome-card"><p>Current status</p><h2>{online ? 'You are available.' : 'You are offline.'}</h2><p>{online ? 'DTS dispatch can assign eligible trips.' : 'Go online only when ready and assigned to an approved vehicle.'}</p><button className="button button-primary" onClick={() => setOnline(!online)}>{online ? 'Go offline' : 'Go online'}</button></section><section className="membership-summary"><p className="overline">Assigned vehicle · Demo</p><h3>Toyota Camry</h3><p>DTS-PRE-002 · Petrol · Documents verified</p><div className="credit-row"><span>Today’s trips<strong>3</strong></span><span>Safety score<strong>94</strong></span></div></section></div><div className="quick-grid">{[[CalendarClock,'Next trip','09:30 · Maitama'],[MapPin,'Navigate','Map not connected'],[ShieldCheck,'Passenger check','Verify before start'],[Siren,'SOS & support','Escalation tools']].map(([Icon,title,text]) => <article className="quick-card" key={String(title)}><Icon size={20}/><strong>{String(title)}</strong><small>{String(text)}</small></article>)}</div><section className="panel"><div className="panel-head"><h3>Assigned trip workflow</h3><button onClick={requestLocation}>Enable trip location</button></div><div className="trip-row"><span className="trip-icon"><Clock3 size={16}/></span><div><strong>Airport pickup · Booking DTS-DEMO-1042</strong><small>Accept → Navigate → Arrive → Verify → Start → Complete</small></div><span>Assigned</span></div><div className="trip-row"><span className="trip-icon"><MapPin size={16}/></span><div><strong>Location permission</strong><small>{locationState}</small></div><span>Private</span></div></section></AppShell>
}

export function FleetDashboard() {
  return <AppShell kind="fleet" title="Fleet management" subtitle="Vehicles, chauffeurs, costs and compliance"><div className="kpi-grid">{[[CarFront,'Vehicles','5 demo'],[Gauge,'Available','3'],[Fuel,'Service due','1'],[TrendingUp,'Utilisation','Demo only']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>Illustrative development record</small></article>)}</div><div className="content-grid"><section className="panel"><div className="panel-head"><h3>Live fleet map</h3><button>Map settings</button></div><div className="ops-map"><div className="map-empty"><MapPin size={24}/><strong>Map integration not connected</strong><small>Configure Mapbox or Google Maps to view authorised fleet locations.</small></div></div></section><section className="panel"><div className="panel-head"><h3>Fleet attention</h3></div><div className="trip-row"><span className="trip-icon"><AlertTriangle size={16}/></span><div><strong>Corolla · service due</strong><small>Next service date approaching</small></div><span>Review</span></div><div className="trip-row"><span className="trip-icon"><BatteryCharging size={16}/></span><div><strong>EV telemetry</strong><small>Provider not connected</small></div><span>Offline</span></div></section></div><section className="panel table-panel" style={{marginTop:20}}><div className="panel-head"><h3>Managed vehicles</h3><button>Add vehicle</button></div><table className="data-table"><thead><tr><th>Vehicle</th><th>Class</th><th>Fuel</th><th>Chauffeur</th><th>Status</th></tr></thead><tbody><tr><td>Toyota Corolla · Demo</td><td>City</td><td>Petrol</td><td>Chinedu Okafor</td><td><span className="status-badge">Available</span></td></tr><tr><td>Toyota Camry · Demo</td><td>Premium</td><td>Petrol</td><td>Musa Bello</td><td><span className="status-badge amber">Assigned</span></td></tr><tr><td>Toyota Hiace · Demo</td><td>Executive Bus</td><td>Diesel</td><td>Unassigned</td><td><span className="status-badge gray">Maintenance</span></td></tr></tbody></table></section></AppShell>
}

export function CorporateDashboard() {
  return <AppShell kind="corporate" title="Corporate mobility" subtitle="Policies, riders, approvals and billing"><div className="kpi-grid">{[[Users,'Active riders','24'],[CalendarClock,'Trips this month','38'],[CircleDollarSign,'Monthly spend','Demo'],[WalletCards,'Invoices due','1']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>Demo corporate account</small></article>)}</div><div className="content-grid"><section className="panel table-panel"><div className="panel-head"><h3>Booking approvals</h3><button>Manage policy</button></div><table className="data-table"><thead><tr><th>Rider</th><th>Journey</th><th>Class</th><th>Policy</th><th>Status</th></tr></thead><tbody><tr><td>Ifeoma Adeyemi</td><td>Airport transfer</td><td>Premium</td><td>Within limit</td><td><span className="status-badge amber">Pending</span></td></tr><tr><td>Tunde Balogun</td><td>Office recurring</td><td>City</td><td>Approved route</td><td><span className="status-badge">Approved</span></td></tr></tbody></table></section><section className="panel"><div className="panel-head"><h3>Account controls</h3></div>{['Employee limits','Department budgets','Vehicle class rules','Approval levels'].map((item) => <div className="trip-row" key={item}><span className="trip-icon"><Building2 size={15}/></span><div><strong>{item}</strong><small>Configurable by company admin</small></div><span>Manage</span></div>)}</section></div></AppShell>
}

export function AdminDashboard() {
  return <AppShell kind="admin" title="DTS operations control" subtitle="Authorised administration and live coordination"><div className="kpi-grid">{[[CircleDollarSign,'Revenue today','No live data'],[CarFront,'Active trips','0'],[Users,'Active members','Demo'],[ShieldCheck,'Open incidents','0']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>{String(value).includes('No') ? 'Payment integration not connected' : 'Demo environment'}</small></article>)}</div><div className="content-grid"><section className="panel"><div className="panel-head"><h3>Live operations centre</h3><Link to="/admin/live-operations">Open full view</Link></div><div className="ops-map"><div className="map-empty"><MapPin size={24}/><strong>Fleet location unavailable</strong><small>No fabricated GPS is shown. Connect a map provider and authorised location stream.</small></div></div></section><section className="panel"><div className="panel-head"><h3>Operations queue</h3></div>{['Incoming requests','Scheduled airport trips','Shared matches','SOS alerts'].map((item,index) => <div className="trip-row" key={item}><span className="trip-icon">{index === 3 ? <Siren size={15}/> : <CalendarClock size={15}/>}</span><div><strong>{item}</strong><small>Operational review queue</small></div><span>{index === 1 ? '2 demo' : '0'}</span></div>)}</section></div></AppShell>
}
