import { useState } from 'react'
import { Link } from '@tanstack/react-router'
import { CalendarClock, CarFront, MapPin, Plane, ShieldCheck, Siren, Users, Sparkles, WalletCards } from 'lucide-react'
import { AppShell } from './AppShell'
import { EmptyState } from './EmptyState'

export function CustomerDashboard() {
  const [available, setAvailable] = useState(false)
  const [locationState, setLocationState] = useState('Not included in matching')
  function toggleAvailability() {
    if (available) { setAvailable(false); setLocationState('Not included in matching'); return }
    if (!navigator.geolocation) { setLocationState('Location is not supported on this device'); return }
    setLocationState('Requesting location permission…')
    navigator.geolocation.getCurrentPosition(() => { setAvailable(true); setLocationState('Permission granted · awaiting eligible zone and route lookup') },() => setLocationState('Location permission was not granted'),{enableHighAccuracy:true,maximumAge:15_000,timeout:10_000})
  }
  return <AppShell kind="customer" title="My mobility" subtitle="FASTRIDES · Your dream destination...on time.">
    <div className="dashboard-hero"><section className="welcome-card"><p>Welcome</p><h2>Where can we take you today?</h2><p>Book now, schedule ahead or arrange a journey for someone else.</p><Link to="/app/book" className="button button-primary">Book a ride <ArrowRightIcon/></Link></section><section className="membership-summary"><p className="overline">Current membership</p><h3>Not subscribed yet</h3><p>Membership pricing is configured by FASTRIDES operations. Requests are recorded and processed once billing is connected.</p><div className="credit-row"><span>Ride credits<strong>0 available</strong></span><span>Wallet<strong>₦0.00</strong></span></div></section></div>
    <div className="quick-grid">{[[CalendarClock,'Schedule ride','Plan ahead'],[Plane,'Airport transfer','Flight-ready flow'],[Users,'Book for someone','Family or guest'],[Sparkles,'Chauffeur service','By the hour']].map(([Icon,title,text]) => <Link to="/app/book" className="quick-card" key={String(title)}><Icon size={20}/><strong>{String(title)}</strong><small>{String(text)}</small></Link>)}</div>
    <div className="content-grid"><section className="panel"><div className="panel-head"><h3>Upcoming &amp; recent</h3><Link to="/app/trips">View all</Link></div><EmptyState icon={CarFront} title="No trips yet." body="Booked and completed journeys appear here once you make your first booking." action={<Link className="button button-primary" to="/app/book">Book a ride</Link>}/></section><section className="availability-panel"><Users size={22}/><h3>Availability Mode</h3><p>Join controlled shared-ride matching at supported pickup points. Location is used only with your permission while active.</p><div className="toggle-row"><span>{available ? 'Available for matching' : 'Currently off'}</span><button className={`switch ${available ? 'on' : ''}`} onClick={toggleAvailability} aria-label="Toggle Availability Mode" /></div><div className="integration-state"><MapPin size={13}/>{locationState}</div></section></div>
  </AppShell>
}

function ArrowRightIcon() { return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg> }

export function DriverDashboard() {
  const [online, setOnline] = useState(false)
  const [locationState, setLocationState] = useState('Location off')
  function requestLocation() {
    if (!navigator.geolocation) { setLocationState('Location unavailable'); return }
    setLocationState('Requesting permission…')
    navigator.geolocation.getCurrentPosition(() => setLocationState('Permission granted · updates wait for an authorised active trip'),() => setLocationState('Permission not granted'),{enableHighAccuracy:true,maximumAge:5_000,timeout:10_000})
  }
  return <AppShell kind="driver" title="Chauffeur workspace" subtitle="Simple, safe trip operations"><div className="dashboard-hero"><section className="welcome-card"><p>Current status</p><h2>{online ? 'You are available.' : 'You are offline.'}</h2><p>{online ? 'FASTRIDES dispatch can assign eligible trips.' : 'Go online only when ready and assigned to an approved vehicle.'}</p><button className="button button-primary" onClick={() => setOnline(!online)}>{online ? 'Go offline' : 'Go online'}</button></section><section className="membership-summary"><p className="overline">Assigned vehicle</p><h3>Not assigned yet</h3><p>Your assigned vehicle appears here once fleet operations assign you one.</p><div className="credit-row"><span>Today’s trips<strong>0</strong></span><span>Safety score<strong>—</strong></span></div></section></div><div className="quick-grid">{[[CalendarClock,'Next trip','No upcoming assignments'],[MapPin,'Navigate','Map not connected'],[ShieldCheck,'Passenger check','Verify before start'],[Siren,'SOS & support','Escalation tools']].map(([Icon,title,text]) => <article className="quick-card" key={String(title)}><Icon size={20}/><strong>{String(title)}</strong><small>{String(text)}</small></article>)}</div><section className="panel"><div className="panel-head"><h3>Assigned trip workflow</h3><button onClick={requestLocation}>Enable trip location</button></div><div className="trip-row"><span className="trip-icon"><MapPin size={16}/></span><div><strong>Location permission</strong><small>{locationState}</small></div><span>Private</span></div><EmptyState icon={CarFront} title="No active assignment." body="Accepted assignments and their trip workflow appear here when dispatch offers you a trip."/></section></AppShell>
}

export function FleetDashboard() {
  return <AppShell kind="fleet" title="Fleet management" subtitle="Vehicles, chauffeurs, costs and compliance"><div className="kpi-grid">{[[CarFront,'Vehicles','0'],[CarFront,'Available','0'],[CalendarClock,'Service due','0'],[Users,'Chauffeurs','0']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>Live counts from fleet records</small></article>)}</div><div className="content-grid"><section className="panel"><div className="panel-head"><h3>Live fleet map</h3><button>Map settings</button></div><div className="ops-map"><div className="map-empty"><MapPin size={24}/><strong>Map integration not connected</strong><small>Configure a map provider to view authorised fleet locations. No position data is fabricated.</small></div></div></section><section className="panel"><div className="panel-head"><h3>Fleet attention</h3></div><EmptyState icon={CarFront} title="No vehicles have been added." body="Vehicle records, compliance dates and service schedules appear once vehicles are registered."/></section></div><section className="panel table-panel" style={{marginTop:20}}><div className="panel-head"><h3>Managed vehicles</h3><button>Add vehicle</button></div><table className="data-table"><thead><tr><th>Vehicle</th><th>Class</th><th>Fuel</th><th>Chauffeur</th><th>Status</th></tr></thead><tbody><tr><td colSpan={5}><EmptyState icon={CarFront} title="No vehicles have been added." body={false}/></td></tr></tbody></table></section></AppShell>
}

export function CorporateDashboard() {
  return <AppShell kind="corporate" title="Corporate mobility" subtitle="Policies, riders, approvals and billing"><div className="kpi-grid">{[[Users,'Active riders','0'],[CalendarClock,'Trips this month','0'],[WalletCards,'Invoices due','0'],[Users,'Departments','0']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>Counts come from account records</small></article>)}</div><div className="content-grid"><section className="panel table-panel"><div className="panel-head"><h3>Booking approvals</h3><button>Manage policy</button></div><table className="data-table"><thead><tr><th>Rider</th><th>Journey</th><th>Class</th><th>Policy</th><th>Status</th></tr></thead><tbody><tr><td colSpan={5}><EmptyState icon={Users} title="No approvals pending." body={false}/></td></tr></tbody></table></section><section className="panel"><div className="panel-head"><h3>Account controls</h3></div>{['Employee limits','Department budgets','Vehicle class rules','Approval levels'].map((item) => <div className="trip-row" key={item}><span className="trip-icon"><Users size={15}/></span><div><strong>{item}</strong><small>Configurable by company admin</small></div><span>Manage</span></div>)}</section></div></AppShell>
}

export function AdminDashboard() {
  return <AppShell kind="admin" title="FASTRIDES operations control" subtitle="Authorised administration and live coordination"><div className="kpi-grid">{[[Users,'Customers','0'],[CarFront,'Active trips','0'],[ShieldCheck,'Open incidents','0'],[CarFront,'Vehicles','0']].map(([Icon,label,value]) => <article className="kpi-card" key={String(label)}><span>{String(label)}<Icon size={17}/></span><strong>{String(value)}</strong><small>Live counts from the database</small></article>)}</div><div className="content-grid"><section className="panel"><div className="panel-head"><h3>Live operations centre</h3><Link to="/admin/live-operations">Open full view</Link></div><div className="ops-map"><div className="map-empty"><MapPin size={24}/><strong>Fleet location unavailable</strong><small>No fabricated GPS is shown. Connect a map provider and authorised location stream.</small></div></div></section><section className="panel"><div className="panel-head"><h3>Operations queue</h3></div>{['Incoming requests','Scheduled airport trips','Shared matches','SOS alerts'].map((item,index) => <div className="trip-row" key={item}><span className="trip-icon">{index === 3 ? <Siren size={15}/> : <CalendarClock size={15}/>}</span><div><strong>{item}</strong><small>Operational review queue</small></div><span>0</span></div>)}</section></div></AppShell>
}